name: "> assert foo"
description: "Notes on Coding, Linux and more"
author: "Worblehat"
markdown: rdiscount
#url: "http://localhost:4000"
url: "http://worblehat.github.io"
exclude: [README.md]
excerpt_separator: ""   #Disable automatic excerpts
permalink: /:title
